### ISSUE TITLE
Main类中 sclawByDetail方法用jsoup解析页面，为什么sclawByAPI方法 又去解析xml，用jsoup不行吗？

### ISSUE THREAD

**Issue by victorysoft** [Benjamin1901/Spider_DouBan_Book#1]

**Comment by victorysoft** [comment]
sclawByAPI 给的url不正确；“sclawByAPI  根据url去api中爬数据”  这句话什么意思？

**Comment by Benjamin1901** [comment]
1、因为豆瓣原理有一个API是这样的 http://api.douban.com/book/subject/4123377 ，里面的有大部分的xml格式的数据，但是没有价格和评论的数据，直接爬这个API获取的数据速度容易而且IP不易被封。

2、我们通过爬取的图书ID，拼接成这样的url：http://api.douban.com/book/subject/4123377， 传给接口这个sclawByAPI。

3、这几天官方的这个API可能有点问题.....分享一个其它网友的API，传入图书id就能拿到数据 https://douban.uieee.com/v2/book/1220562

**Comment by victorysoft** [comment]
首先，十分感谢。
最近在看java爬虫相关的代码，在github上搜到你的了，感觉你写的很好，就拿来学习一下。有些不懂的地方就提问了，没想到你回答的那么详细，十分感动。
今天去豆瓣看，之前的豆瓣图书API果然给封了，按照你重新给的ip，我又重新写了一个解析json的方法。正在修改中，估计过几天就能完成。
最后还是 谢谢

**Comment by Benjamin1901** [comment]
> 首先，十分感谢。
> 最近在看java爬虫相关的代码，在github上搜到你的了，感觉你写的很好，就拿来学习一下。有些不懂的地方就提问了，没想到你回答的那么详细，十分感动。
> 今天去豆瓣看，之前的豆瓣图书API果然给封了，按照你重新给的ip，我又重新写了一个解析json的方法。正在修改中，估计过几天就能完成。
> 最后还是 谢谢

共同进步😁~
